### ISSUE TITLE
Docked geometry messed up

### ISSUE THREAD

**Issue by eventfulsean** [oddt/oddt#108] opened 2019-10-10 19:12 UTC
Hi! Thanks to the developer putting together the ODDT library of tools. It has the potential to be very impactful.

I'm running into an issue with vina docking where it produces distorted ligand structures (see screenshot). I compared with running independently installed Vina 1.1.2 and it works expected. I'm using identical protein.pdbqt and ligand.pdbqt and xyz parameters.

Command:
time oddt_cli --dock autodock_vina --receptor recep.pdbqt --center '(9.50,-53.29,2.64)' --size '(70,70,70)' --exhaustiveness 5 --seed 123 ligand.pdbqt -o pdbqt -O test.pdbqt

Original ligand.pdbqt
![image](https://user-images.githubusercontent.com/41400337/66599352-fae9c680-eb70-11e9-96f8-068ff0454209.png)

Output:
Docked ligand.pdbqt
![image](https://user-images.githubusercontent.com/41400337/66599348-f9200300-eb70-11e9-9f9d-bbdd1b571359.png)

Any thoughts would be much appreciated!

**Comment by eventfulsean** [comment] 2019-10-10 19:19
Just to add, i'm using openbabel 2.4.1.

**Comment by mwojcikowski** [comment] 2019-10-11 20:41
Which version of the oddt are you using? I would recommend the latest git one, until we make 0.7 release. Could you also share the pdbqt files so that I can reproduce your error?

**Comment by maclandrol** [comment] 2019-10-17 22:25
I have checked and this error exists for rdkit too.  The problem is coming from this line that copy the coordinates from the docked ligand to the original source. 

https://github.com/oddt/oddt/blob/1426b63cf8fe5a69cf87b676a74a480f0edcc209/oddt/docking/AutodockVina.py#L293 

It seems that assuming `# ... the order of atoms match between ligands` is not true.
Can we just return the docked ligand as it is ?

**Comment by maclandrol** [comment] 2019-10-18 01:12
@mwojcikowski , is the reordering performed for openbabel > 2.4.0 necessary ? 
Reading both the ligand and docked ligand from the tempfile directly is working fine:

```python
def dock(self, ligands, protein=None):
    """Automated docking procedure.

    Parameters
    ----------
    ligands: iterable of oddt.toolkit.Molecule objects
        Ligands to dock

    protein: oddt.toolkit.Molecule object or None
        Protein object to be used. If None, then the default one
        is used, else the protein is new default.

    Returns
    -------
    ligands : array of oddt.toolkit.Molecule objects
        Array of ligands (scores are stored in mol.data method)
    """
    if protein:
        self.set_protein(protein)
    if not self.protein_file:
        raise IOError("No receptor.")
    if is_molecule(ligands):
        ligands = [ligands]
    ligand_dir = mkdtemp(dir=self.tmp_dir, prefix='ligands_')
    output_array = []
    for n, ligand in enumerate(ligands):
        check_molecule(ligand, force_coords=True)
        ligand_file = write_vina_pdbqt(ligand, ligand_dir, name_id=n)
        ligand_outfile = ligand_file[:-6] + '_out.pdbqt'
        try:
            scores = parse_vina_docking_output(
                subprocess.check_output([self.executable, '--receptor',
                                         self.protein_file,
                                         '--ligand', ligand_file,
                                         '--out', ligand_outfile] +
                                        self.params +
                                        ['--cpu', str(self.n_cpu)],
                                        stderr=subprocess.STDOUT))
        except subprocess.CalledProcessError as e:
            sys.stderr.write(e.output.decode('ascii'))
            if self.skip_bad_mols:
                continue  # TODO: print some warning message
            else:
                raise Exception('Autodock Vina failed. Command: "%s"' %
                                ' '.join(e.cmd))

        # docked conformations may have wrong connectivity - use source ligand
        if is_openbabel_molecule(ligand):
            ligand = next(oddt.toolkit.readfile('pdbqt', ligand_file))
            if 'REMARK' in ligand.data:
                del ligand.data['REMARK']

        docked_ligands = oddt.toolkit.readfile('pdbqt', ligand_outfile)
        for docked_ligand, score in zip(docked_ligands, scores):
            # HACK: copy docked coordinates onto source ligand
            clone = ligand.clone
            clone.clone_coords(docked_ligand)
            clone.data.update(score)

            # Calculate RMSD to the input pose
            try:
                clone.data['vina_rmsd_input'] = rmsd(ligand, clone)
                clone.data['vina_rmsd_input_min'] = rmsd(ligand, clone,
                                                         method='min_symmetry')
            except Exception:
                pass
            output_array.append(clone)
    rmtree(ligand_dir)
    return output_array
```

**Comment by mwojcikowski** [comment] 2019-10-20 21:43
Unfortunately this is not so straightforward, basicaly PDBQT does not store information about the bond orders and molecules can be messed up in many different ways too, hence the mechanism to copy over the conformer back to the original molecule. I will look into this, but it is really weird that you have the same behavior with RDKit, as OB uses very different PDBQT writter. I would expect at least one of them not to fail.

Could you at least share the lingand pdbqt file?

**Comment by eventfulsean** [comment] 2019-10-24 04:57
@mwojcikowski I'm using version 0.6 from the conda channel. I'll try to install the got version and try again, perhaps with rdkit. Is it safer to do a pdbqt to pdbqt conversion rather than coord copy?

I'll share ligand.pdbqt tmr.

**Comment by eventfulsean** [comment] 2019-10-24 18:12
Here's the ligand:

[ligand.pdbqt.txt](https://github.com/oddt/oddt/files/3768884/ligand.pdbqt.txt)

**Comment by mwojcikowski** [comment] 2019-10-24 18:42
Wrong reported version is a known issue, I will fix it with a new release.

I will take a look at the ligand.

**Comment by eventfulsean** [comment] 2019-10-24 19:17
@mwojcikowski quick update. I created a new conda environment and ran:

conda install -c oddt oddt
conda install -c oddt openbabel

**The output ligand looks fine!**

But the problem re-occurs if I then install via:
**python setup.py install**

**Comment by mwojcikowski** [comment] 2019-10-24 19:30
It might be that particular change that broke it for you: 0208f21f59745602e2000627407a14717c0ac435

Need to investigate it.

**Comment by parkc23** [comment] 2020-07-07 11:35
I get the same messed-up molecules even if they are written to sdf files by using oddt_cli. The program versions should be the latest as they were installed a month ago via conda.

**Comment by mwojcikowski** [comment] 2020-07-07 18:06
@parkc23 Could you please provide a ligand with such issue? Also please specify the toolkit you use and its version (OB/RDKit).

**Comment by parkc23** [comment] 2020-07-07 19:15
Thanks for the prompt attention. Please find below for the input and output files.
[in_out.sdf.tar.gz](https://github.com/oddt/oddt/files/4886659/in_out.sdf.tar.gz)

By the way, how do I check the versions for OB and RDKit? I looked into the anaconda/pkgs folder, and found these below. (I installed these via conda recently)
openbabel-2.4.1-py27_3
rdkit-2017.09.1-py27_1

**Comment by mwojcikowski** [comment] 2020-07-07 20:41
I managed to reproduce the problem. To solve it just upgrade to OpenBabel 3.0 `conda install -c conda-forge openbabel`. In the meantime I will check if there is anything on our side that I can do to fix it.

**Comment by parkc23** [comment] 2020-07-08 05:38
I uninstalled the previous version and installed openbabel-3.1.1-py38hf4b5c11_0 by "conda install -c conda-forge openbabel", but when I ran oddt_cli, I got the error below. Could you take a look?

Traceback (most recent call last):
  File "~/anaconda2/bin/oddt_cli", line 283, in <module>
    main()
  File "~/anaconda2/bin/oddt_cli", line 182, in main
    from oddt.toolkits import ob
  File "~/anaconda2/lib/python2.7/site-packages/oddt/toolkits/ob.py", line 24, in <module>
    import pybel
ImportError: No module named pybel

**Comment by parkc23** [comment] 2020-07-08 07:49
I installed it by "conda install -c conda-forge openbabel", but when I ran oddt_cli, I got the following error.
Could you take a look?

Traceback (most recent call last):
  File "/home/cmpark/anaconda2/bin/oddt_cli", line 283, in <module>
    main()
  File "/home/cmpark/anaconda2/bin/oddt_cli", line 182, in main
    from oddt.toolkits import ob
  File "/home/cmpark/anaconda2/lib/python2.7/site-packages/oddt/toolkits/ob.py", line 24, in <module>
    import pybel
ImportError: No module named pybel

**Comment by parkc23** [comment] 2020-07-08 07:50
I installed it by "conda install -c conda-forge openbabel", but when I ran oddt_cli, I got the following error.
Could you take a look?

Traceback (most recent call last):
File "~/anaconda2/bin/oddt_cli", line 283, in
main()
File "~/anaconda2/bin/oddt_cli", line 182, in main
from oddt.toolkits import ob
File "~/anaconda2/lib/python2.7/site-packages/oddt/toolkits/ob.py", line 24, in
import pybel
ImportError: No module named pybel

**Comment by parkc23** [comment] 2020-07-08 08:58
I installed OpenBabel 3.0, but got an error below when I ran oddt_cli. Could you take a look?

Traceback (most recent call last):
  File "/home/anaconda2/bin/oddt_cli", line 283, in <module>
    main()
  File "/home/anaconda2/bin/oddt_cli", line 182, in main
    from oddt.toolkits import ob
  File "/home/anaconda2/lib/python2.7/site-packages/oddt/toolkits/ob.py", line 24, in <module>
    import pybel
ImportError: No module named pybel

**Comment by parkc23** [comment] 2020-07-10 15:04
Hi,
Is it ok to ignore these warnings harmless?

1. miniconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.tree.tree module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.

2. miniconda3/lib/python3.7/site-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.20.3 when using version 0.23.1. This might lead to breaking code or invalid results. Use at your own risk.

3. miniconda3/lib/python3.7/site-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator RandomForestRegressor from version 0.20.3 when using version 0.23.1. This might lead to breaking code or invalid results. Use at your own risk.

Thanks a lot.

**Comment by mwojcikowski** [comment] 2020-07-10 19:22
The first one you can ignore, the second one suggests that you should retrain your models. In general it should work, but there is no harm to retrain them to be extra cautious.

Openbabel <3.0 was retired in #134, thus I'm closing this Issue. If you have further unrelated questions please open another issue.

**Closed by mwojcikowski** 2020-07-10 19:22 UTC
